"""initial_schema

Revision ID: 6277d4b58047
Revises: 
Create Date: 2026-07-03 12:25:28.468274

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6277d4b58047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_daily',
    sa.Column('location_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rainfall_mm', sa.Double(), nullable=True),
    sa.Column('tmean_c', sa.Double(), nullable=True),
    sa.Column('tmin_c', sa.Double(), nullable=True),
    sa.Column('tmax_c', sa.Double(), nullable=True),
    sa.Column('relative_humidity', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('location_id', 'date')
    )
    op.create_table('dataset_registry',
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('dataset_name', sa.Text(), nullable=False),
    sa.Column('source_organization', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('download_date', sa.Date(), nullable=True),
    sa.Column('coverage_period', sa.Text(), nullable=True),
    sa.Column('file_checksum', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('organizations',
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('organization_name', sa.Text(), nullable=False),
    sa.Column('organization_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('sites',
    sa.Column('site_id', sa.Text(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('coordinate_source', sa.Text(), nullable=True),
    sa.Column('coordinate_quality', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('field_visits',
    sa.Column('visit_id', sa.Text(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('habitat_type', sa.Text(), nullable=True),
    sa.Column('habitat_positive', sa.Boolean(), nullable=True),
    sa.Column('sampling_effort_type', sa.Text(), nullable=True),
    sa.Column('sampling_effort_value', sa.Double(), nullable=True),
    sa.Column('quality_flag', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_table('resistance_test_replicates',
    sa.Column('replicate_id', sa.Text(), nullable=False),
    sa.Column('source_row_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('test_month', sa.Integer(), nullable=True),
    sa.Column('test_year', sa.Integer(), nullable=True),
    sa.Column('species_raw', sa.Text(), nullable=True),
    sa.Column('species_clean', sa.Text(), nullable=True),
    sa.Column('insecticide_tested', sa.Text(), nullable=True),
    sa.Column('concentration_label', sa.Text(), nullable=True),
    sa.Column('number_exposed', sa.Integer(), nullable=True),
    sa.Column('number_dead_24h', sa.Integer(), nullable=True),
    sa.Column('mortality_rate', sa.Double(), nullable=True),
    sa.Column('control_mortality', sa.Double(), nullable=True),
    sa.Column('resistance_status', sa.Text(), nullable=True),
    sa.Column('quality_flag', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('replicate_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('active_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Text(), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('rule_or_model_version', sa.Text(), nullable=True),
    sa.Column('uncertainty_level', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('alert_expiry_date', sa.Date(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=True),
    sa.Column('record_id', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('mosquito_observations',
    sa.Column('observation_id', sa.Text(), nullable=False),
    sa.Column('visit_id', sa.Text(), nullable=True),
    sa.Column('life_stage', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('species_raw', sa.Text(), nullable=True),
    sa.Column('species_clean', sa.Text(), nullable=True),
    sa.Column('identification_method', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['field_visits.visit_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('response_actions',
    sa.Column('action_id', sa.Text(), nullable=False),
    sa.Column('alert_id', sa.Text(), nullable=True),
    sa.Column('responsible_organization', sa.Text(), nullable=True),
    sa.Column('responsible_user', sa.Text(), nullable=True),
    sa.Column('action_due_date', sa.Date(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('action_status', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=True),
    sa.Column('follow_up_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.ForeignKeyConstraint(['responsible_user'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_actions')
    op.drop_table('mosquito_observations')
    op.drop_table('audit_log')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('resistance_test_replicates')
    op.drop_table('field_visits')
    op.drop_table('sites')
    op.drop_table('organizations')
    op.drop_table('dataset_registry')
    op.drop_table('climate_daily')
    # ### end Alembic commands ###
